# Generated by Django 3.1.7 on 2021-03-07 06:21

import ctapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8)], default='6', max_length=20)),
                ('sec', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('CS', 'CS'), ('EC', 'EC'), ('MECH', 'MECH'), ('EE', 'EE'), ('EX', 'EX'), ('CIVIL', 'CIVIL')], default='IT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('enrollment_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('college_name', models.CharField(choices=[('LNCT', 'LNCT'), ('LNCTS', 'LNCTS'), ('LNCTE', 'LNCTE')], default='LNCT', max_length=10)),
                ('sem', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8)], default='6', max_length=20)),
                ('sec', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('CS', 'CS'), ('EC', 'EC'), ('MECH', 'MECH'), ('EE', 'EE'), ('EX', 'EX'), ('CIVIL', 'CIVIL')], default='IT', max_length=20)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('CS', 'CS'), ('EC', 'EC'), ('MECH', 'MECH'), ('EE', 'EE'), ('EX', 'EX'), ('CIVIL', 'CIVIL')], default='IT', max_length=20)),
                ('sem', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8)], default='6', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('college_name', models.CharField(choices=[('LNCT', 'LNCT'), ('LNCTS', 'LNCTS'), ('LNCTE', 'LNCTE')], default='LNCT', max_length=10)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('CS', 'CS'), ('EC', 'EC'), ('MECH', 'MECH'), ('EE', 'EE'), ('EX', 'EX'), ('CIVIL', 'CIVIL')], default='IT', max_length=20)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.class')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.subject')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='student_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ctapp.models.user_directory_path)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.assignment')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='t_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.teacher'),
        ),
    ]
