# Generated by Django 3.1.7 on 2021-04-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0005_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='timetable',
            field=models.ImageField(default='6a.jpg', upload_to='Class/TimeTable'),
        ),
    ]
