# Generated by Django 3.1.7 on 2021-04-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0006_class_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='timetable',
            field=models.ImageField(default='6a.jpg', upload_to='Time Tables/'),
        ),
        migrations.AlterField(
            model_name='student_submission',
            name='stud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.student', unique=True),
        ),
    ]
