# Generated by Django 3.1.7 on 2021-04-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0007_auto_20210402_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.class')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.subject')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.teacher')),
            ],
        ),
    ]
