# Generated by Django 3.1.7 on 2021-04-03 11:04

import ctapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0009_auto_20210403_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignfile',
            field=models.FileField(default='p.pdf', upload_to=ctapp.models.get_directory_for_assignment_details),
        ),
    ]
