# Generated by Django 3.1.7 on 2021-04-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0011_test_test_for_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_for_sem',
        ),
    ]
