# Generated by Django 3.1.7 on 2021-04-30 08:25

import ctapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0012_remove_test_test_for_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_testsubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=ctapp.models.user_directory_path_for_test)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.student')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.test')),
            ],
        ),
    ]
