# Generated by Django 3.1.7 on 2021-05-03 09:00

import ctapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0013_student_testsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_testsubmission',
            name='report',
            field=models.FileField(default='p.pdf', upload_to=ctapp.models.user_directory_path_for_test_report),
        ),
    ]
