# Generated by Django 3.1.7 on 2021-05-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0014_student_testsubmission_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='form_link',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
