# Generated by Django 3.1.7 on 2021-05-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0015_test_form_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='form_link',
            field=models.CharField(default='Google Link', max_length=1000),
        ),
    ]
